// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
std::string dump_midi_impl(const std::string filename);
extern "C" SEXP _pipopaplot_dump_midi_impl(SEXP filename) {
  BEGIN_CPP11
    return cpp11::as_sexp(dump_midi_impl(cpp11::as_cpp<cpp11::decay_t<const std::string>>(filename)));
  END_CPP11
}
// code.cpp
std::string write_midi_impl(const std::string filename, int tpq, const std::vector<int>& programs, const std::vector<int>& channels, const std::vector<int>& tick_on, const std::vector<int>& tick_off, const std::vector<int>& keys, const std::vector<int>& velocities);
extern "C" SEXP _pipopaplot_write_midi_impl(SEXP filename, SEXP tpq, SEXP programs, SEXP channels, SEXP tick_on, SEXP tick_off, SEXP keys, SEXP velocities) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_midi_impl(cpp11::as_cpp<cpp11::decay_t<const std::string>>(filename), cpp11::as_cpp<cpp11::decay_t<int>>(tpq), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(programs), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(channels), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(tick_on), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(tick_off), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(keys), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(velocities)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pipopaplot_dump_midi_impl",  (DL_FUNC) &_pipopaplot_dump_midi_impl,  1},
    {"_pipopaplot_write_midi_impl", (DL_FUNC) &_pipopaplot_write_midi_impl, 8},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pipopaplot(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
