# Generated by cpp11: do not edit by hand

dump_midi_impl <- function(filename) {
  .Call(`_pipopaplot_dump_midi_impl`, filename)
}

write_midi_impl <- function(filename, tpq, programs, channels, tick_on, tick_off, keys, velocities) {
  .Call(`_pipopaplot_write_midi_impl`, filename, tpq, programs, channels, tick_on, tick_off, keys, velocities)
}
